### ISSUE TITLE
i18n: sidebar layout breaks on specific languages

### ISSUE THREAD

**Issue by jeherve** [Automattic/studio#40]
### Quick summary

When using languages that use longer labels, the layout of the sidebar breaks into 2 lines.

### Steps to reproduce

1. Install the Studio app when using French as your interface language
2. Notice the buttons at the bottom of the sidebar

### What you expected to happen

I expected the sidebar width to adjust to the length of the different labels

### What actually happened

![Capture d’écran 2024-04-26 à 11 37 59](https://github.com/Automattic/studio/assets/426388/ce0f041d-2ef5-4e20-b88b-579c60cb644d)

### Impact

Some (< 50%)

### Available workarounds?

No but the app is still usable

### Platform

Mac Silicon

**Comment by katinthehatsite** [comment]
I spent some time looking into what we could do with this. Here are some options:

* We are currently setting the sidebar to `basis-52` which is `208px` ([flex basis info](https://tailwindcss.com/docs/flex-basis)). One thing we can explore is increasing the `basis` to something like `56` which would make the longer words fit on one line. Here is a small exploration of what it would look like:

<img width="912" alt="Captura de pantalla 2024-05-06 a las 16 26 06" src="https://github.com/Automattic/studio/assets/25575134/9c33b988-2da1-48c1-a6c3-a4c3359593aa">

This is not a perfect solution though because if the word is very long, it would still not look great. I tried in a couple of main languages and it looked okay though but it is something to keep in mind.

* Alternatively, we can set the `max-width` and `min-width` on the sidebar and make it size based on what is inside it. I only explored this briefly today, I want to check this more.

I think ultimately my question is - are we okay with changing the width of the sidebar (in either option 1 or option 2) - and if we are, what is the max-width that we might want it to allow to go to? I think my main concern is the sidebar becoming overpowering if it gets too wide. @matt-west what are your thoughts? Thanks!

**Comment by wojtekn** [comment]
What if we work on alignment to make the 'Se connecter' text behave in a similar way to the '1 site running' and 'Stop all' texts displayed above? This is how it looks in Polish:

<img width="219" alt="Zrzut ekranu 2024-05-7 o 08 42 23" src="https://github.com/Automattic/studio/assets/727413/e60a648e-1cc4-41d0-94d1-a41cbc456060">

**Comment by katinthehatsite** [comment]
I tried that too @wojtekn 😅 It is one of the options I am considering e.g. leave the sidebar as is and align the words. One thing with that is that the WordPress logo will always stay on one line and `Se connecter` or `Iniciar session` would be on two as opposed to sites running and stop all buttons above that both break on two lines so it creates some sort of visual parity. In our case, it would still be one line word vs. two lines (in some languages) which I think is ultimately where the impression of the broken layout is coming from. 

I see both downsides and upsides to both options (align words or changing the sidebar). My main concern is that I can't be 100% confident how the sidebar will behave in every OS so I prefer to keep it fixed and not touch it if possible. I will wait for @matt-west to give his input and we can go from there 😅

**Comment by wojtekn** [comment]
> One thing with that is that the WordPress logo will always stay on one line and Se connecter or Iniciar session would be on two as opposed to sites running and stop all buttons above that both break on two lines so it creates some sort of visual parity. In our case, it would still be one line word vs. two lines (in some languages) which I think is ultimately where the impression of the broken layout is coming from.

I think it's not a valid assumption, as in some languages, the phrase displayed on the left can use one line, while the phrase on the right can be broken into two lines.

> My main concern is that I can't be 100% confident how the sidebar will behave in every OS so I prefer to keep it fixed and not touch it if possible.

Correct, and extending the width won't rule it out as always there can be language with longer phrase.

**Comment by katinthehatsite** [comment]
> I think it's not a valid assumption, as in some languages, the phrase displayed on the left can use one line, while the phrase on the right can be broken into two lines.

Yep, sorry, I meant for the languages in which it breaks on two lines that it will always be two lines vs. one line (not all languages 😅 ). 

> Correct, and extending the width won't rule it out as always there can be language with longer phrase.

Alright, let's align the words instead 👍

**Comment by matt-west** [comment]
Is it possible to allow users to resize the sidebar? That might be a better approach than trying to automatically size given that we don't know how long site names will be.

Here's an example from VS Code:

https://github.com/Automattic/studio/assets/417538/644853e4-e31c-4ed0-ae53-890fe4d9b02c

(Ignore the part where the sidebar disappears, we don't need that interaction in Studio.)

**Comment by wojtekn** [comment]
> Is it possible to allow users to resize the sidebar? That might be a better approach than trying to automatically size given that we don't know how long site names will be.

We could explore it separately. In the end, it still makes sense to improve it for a narrow sidebar width, as users who can resize the sidebar could keep using the narrow one.

**Comment by katinthehatsite** [comment]
I agree with @wojtekn - I briefly took a look and it would need quite a bit of a refactor but it is probably possible. I suggest we open a different issue as this feels like a separate feature.

**Comment by matt-west** [comment]
Makes sense. Let's fix the alignment instead then.

**Comment by katinthehatsite** [comment]
I merged the fix for sidebar alignment and added a new issue where we can discuss if adding an option to resize the sidebar is something we might want to pursue. I will close this for now.
