### ISSUE TITLE
Unable to upload media

### ISSUE THREAD

**Issue by t-hamano** [Automattic/studio#45]
### Quick summary

Note: I forked and built this repository and tested it on WindowsOS. So this issue may be specific to Windows OS.

![image](https://github.com/Automattic/studio/assets/54422211/bdbd4170-9561-4c1e-a3a8-c072bc680bdb)

Depending on how the media was uploaded, one error can occur here:

https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2395

After further investigation, I realized that the `wp_upload_dir()` function returns a path that does not exist.

```
var_dump( wp_upload_dir() );

array(6) {
  ["path"]=>
  string(40) "/var/www/html/wp-content/uploads/2024/04"
  ["url"]=>
  string(48) "http://localhost:8882/wp-content/uploads/2024/04"
  ["subdir"]=>
  string(8) "/2024/04"
  ["basedir"]=>
  string(32) "/var/www/html/wp-content/uploads"
  ["baseurl"]=>
  string(40) "http://localhost:8882/wp-content/uploads"
  ["error"]=>
  string(102) "Unable to create directory wp-content/uploads/2024/04. Is its parent directory writable by the server?"
}

```

I have WordPress installed on `D:\_wp-studio\`, so these paths don't exist.

### Steps to reproduce

Try to upload media on WindowsOS.

### What you expected to happen

The media will be uploaded successfully.

### What actually happened

An error will be logged.

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Windows

### Logs or notes

- OS: Windows 11
- Studio version: 1.0.0

**Comment by t-hamano** [comment]
I found that a similar error has been reported in wp-now.

https://github.com/WordPress/playground-tools/issues/121

**Comment by fluiddot** [comment]
I also encountered this issue. In my case, it worked after restarting the site four times:

**Steps:**
1. Start a site.
2. Upload an image. **[First attempt]**
3. `uploads` folder is created and the upload fails.
4. Restart the site. 
5. Upload an image. **[Second attempt]**
6. `uploads/2024` folder is created and the upload fails.
7. Restart the site.
8. Upload an image. **[Third attempt]**
9. `uploads/2024/04` folder is created and the upload fails.
10. Restart the site.
11. Upload an image. **[Fourth attempt]** 
12. Image is uploaded 🎊 .

After delving deeper into debugging, I've come to realize that the issue stems from the permissions set when creating a directory in [`wp_mkdir_p`](https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2026-L2036), particularly the part where it utilizes the parent directory's permissions for the new directory ([reference](https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2076-L2082)). Upon comparing the results between macOS and Windows, I noticed a discrepancy:

**macOS**:
- PHP function [mkdir](https://www.php.net/manual/en/function.mkdir.php): By default it uses the value `0777` for permissions.
- WordPress function [wp_mkdir_p](https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2026-L2036): It uses `0755` for permissions, obtained from the parent's directory.

For both cases, all directories are created ✅ .

**Windows**:

- PHP function [mkdir](https://www.php.net/manual/en/function.mkdir.php): By default it uses the value `0777` for permissions. It creates the directories as expected ✅.
- WordPress function [wp_mkdir_p](https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2026-L2036): It uses `066` for permissions, obtained from the parent's directory. **Although it sets `read` and `write` permissions, not allowing `execute` permission in a directory implies that it can't be accessed ❌ .**

This appears to be the root cause of the issue with uploading media. It's intriguing because, according to the PHP documentation, `mkdir` disregards the permission parameter ([reference](https://www.php.net/manual/en/function.mkdir.php)). Hence, in theory, on Windows, any permission value passed to the function shouldn't impact the creation. In this context, I verified the value of the constant `PHP_OS` and found it returns `Linux` for both macOS and Windows platforms.

I'm unsure about the feasibility and potential consequences of modifying the value of `PHP_OS` to exclude permissions when creating a directory. Alternatively, we could explore patching WordPress to prevent the utilization of permissions in `wp_mkdir_p`.

**Comment by fluiddot** [comment]
Apart from forcing a specific `PHP_OS` version, I'd like to propose other alternatives that might be simpler:

### 1 - Patch the `wp-includes/functions.php`

This solution primarily involves updating the functions.php file to refrain from using permissions when creating a directory ([reference](https://github.com/WordPress/wordpress-develop/blob/2074392c5cb15be2dec399c2a6efb2c60fbb671c/src/wp-includes/functions.php#L2076-L2098)). This aligns with the expected behavior of `mkdir` on Windows. We could apply the patch at various points, but the most suitable might be when starting a site.

However, patching the file might not be as straightforward as it seems, particularly if the code is different between WordPress versions.

### 2 - Patch Node's PHP runtimes

This approach delves into addressing the problem at a lower level. I observed that file system functions exposed to PHP in JavaScript, including the following ones, appear to pose issues when running on Windows:

- [`mkdir`](https://github.com/WordPress/wordpress-playground/blob/3fd0315bbf0209cc9f3ab68073bb4533f1c3995d/packages/php-wasm/node/public/php_8_0.js#L4393-L4405) ([This function](https://github.com/emscripten-core/emscripten/blob/63c648fa17be49fa9640d4a40c8ba2f7a9b2d444/src/library_syscall.js#L840-L852) is part o the system calls exposed by Emscripten when compiling PHP)
- [`chmod`](https://github.com/WordPress/wordpress-playground/blob/3fd0315bbf0209cc9f3ab68073bb4533f1c3995d/packages/php-wasm/node/public/php_8_0.js#L3929-L3938) ([This function](https://github.com/emscripten-core/emscripten/blob/63c648fa17be49fa9640d4a40c8ba2f7a9b2d444/src/library_syscall.js#L172-L176) is part o the system calls exposed by Emscripten when compiling PHP)

Consequently, we have an entry point where we could adjust the functionality to avoid using permissions on Windows. This entails patching the `@php-wasm/node` package. I've created a branch where I successfully tested this approach:

The file system functions are exposed 

https://github.com/Automattic/studio/compare/fix/windows-file-permissions

> [!NOTE]
> Note that the adjustments need to be made for every supported PHP version.

**Comment by fluiddot** [comment]
Heads up that I proposed a potential solution in https://github.com/Automattic/studio/pull/66.

**Comment by danielbachhuber** [comment]
🎉 

Thanks @fluiddot !
