### ISSUE TITLE
Studio: Create Block Theme child theme-white screen

### ISSUE THREAD

**Issue by elurie** [Automattic/studio#515]
### Quick summary

The Create Block Theme  plugin 'create child theme command' results in a white screen or msg. The theme you are currently using is not compatible withthe site editorI

### Steps to reproduce

Start Studio
Site Editor (moon icon)
Create Block Theme(Wrench Icon)>Create Theme>Create Child Theme. Name it, and click the "Create Child Theme" button. Get White screen or Message; The theme you are currently using is not compatible with the Site Editor

### What you expected to happen

Using  TT4 theme, and the Create Block Theme plugin

### What actually happened

Error message: Get White screen or Message; "The theme you are currently using is not compatible with the Site Editor". Then after quit Studio and restart the site, Error Message is: 

> Warning: Attempt to read property "content" on null in /var/www/html/wp-includes/blocks/template-part.php on line 73

### Impact

One

### Available workarounds?

No and the app is unusable

**Comment by wojtekn** [comment]
@elurie, thanks for reporting the issue. I've just tested this flow in Studio 1.1.2, and it worked fine. Instead of the white page, I've got the editor reloaded with a new theme. Then, I see a new theme in Appearance -> Themes:

![Screenshot 2024-09-24 at 12 26 03](https://github.com/user-attachments/assets/a0e1aa3d-696b-4563-85ba-9640fc118ded)

Would you mind retesting it using the latest Studio version?

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Studio – Could Not Replicate 
- Tested on Atomic – Could Not Replicate


📌 ACTIONS
- Triaged
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- I'm unable to replicate this using Studio or on an atomic site on WordPress.com. @elurie please reopen if you're still having issues.

**Comment by elurie** [comment]
thanks for your reply, 
I did it a few more times and finally, it started working.
