### ISSUE TITLE
Studio: Offline icon in header is mis-aligned

### ISSUE THREAD

**Issue by matt-west** [Automattic/studio#668]
### Quick summary

When offline, the offline icon displayed in the header bar is not aligned with the sidebar icon.

https://github.com/user-attachments/assets/2d0bb997-4605-4db8-9ffd-d0ea8e7d1b2f

### Steps to reproduce

1. Start Studio
2. Turn off WiFi
3. Hover the sidebar icon
4. Hover the offline icon
5. Note that the offline icon’s hover container is below the sidebar icon’s hover container

### What you expected to happen

The hover containers for the two icons should be the same size and aligned.

### What actually happened

The icons are out of alignment.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by ivan-ottinger** [comment]
Thanks for catching this, Matt.

Turns out this is a regression introduced in https://github.com/Automattic/studio/pull/648. I will remove the `Toggle sidebar` tooltip until we have a better solution for tooltips in https://github.com/Automattic/dotcom-forge/issues/9841.

Related discussion: https://github.com/Automattic/studio/pull/666#issuecomment-2482773118.

Update: Instead of removing the tooltip, I will fix it.
